### ISSUE TITLE
Nanobots broken with Miniloader?

### ISSUE THREAD

**Issue by evandy0** [Nexela/Nanobots#95]
I seem to be unable to upgrade miniloaders in 0.17 with nanobots. I can upgrade them with normal construction bots, so am guessing that this is an issue with nanobots?

Nanobots 3.0.7 & MiniLoader 1.7.7.

Traceback says unknown item name "fast-miniloader-inserter' from nanobots.lua line 73.

**Comment by enchant2** [comment]
I posted this on Bob's Mods forum and they suggested that I also post it here.
-------------
If I use the upgrade planner tool to replace all fast inserters with ultimate stack inserters, it marks the fast inserters, but doesn't replace them.

Latest 17.x Factorio
All mods updated
Although I've researched robots, I haven't made any yet. I'm using nanobots.
As far as I can tell, everything else is getting replaced fine using the planner.
I definitely do have plenty of ultimate stack inserters and nanobots in my inventory.

Edit: I just loaded a game where I had normal construction bots and the fast -> ultimate stack replacement worked fine. So this appears to have something to do with nanobots.

**Comment by maca134** [comment]
Using the upgrade planner and having nanobots equipped errors as they seem to be upgrade to non-existing items. Here is error
https://dl.dropboxusercontent.com/s/4m9u8uecg7z8g1f/LnBUfYf6Ga1WyrFRaIFO.png

**Comment by SuperSandro2000** [comment]
![image](https://user-images.githubusercontent.com/7258858/83342690-8d9ec780-a2f2-11ea-819e-c65856faef71.png)

Reposting to not rely on some users dropbox

**Comment by Nexela** [comment]
This should be fixed for the .18 version of Factorio, unfortunately I do not have the time to backport a fix for .17

**Comment by blueyoshi2015** [comment]
Wanted to stop by to say that this bug still exists in 0.18. I'm getting similar errors to the users above.

![image](https://user-images.githubusercontent.com/57151788/89695118-dd949e80-d8e0-11ea-9c26-24687a85357c.png)
